### ISSUE TITLE
Testing a timeout

### ISSUE THREAD

**Issue by machtyn** [CrowdProcess/superagent-hawk#7]
Is it possible to access the ts value (or any part of the header) to modify so that I may test the timeout feature of my app without having to put a sleep timer in?

**Comment by machtyn** [comment]
Nevermind. I discovered I could take an old Hawk string and use superagent's "set" method to set the authorization value.  in my case:
`request
    .get(url)
    .set("authorization", "Hawk id="myid", ts="value", ...)
    .expect(401, done);`

**Comment by joaojeronimo** [comment]
:+1:
